Properties
Pometry/Raphtory pull request #1103
Opened 2023-07-11 08:56 UTC by ljeub-pometry

### What changes were proposed in this pull request?

Unify the properties api and create Properties and StaticProperties objects

### Why are the changes needed?

Make working with properties easier to use and properties api easier to implement

### Does this PR introduce any user-facing change? If yes is this documented?

yes, all the properties apis are different. Rudimentary docstrings are there but need to be improved

### How was this patch tested?

### Issues

closes #957, #956 

### Are there any further changes required?

2023-07-25 13:14 UTC, miratepuffin requested changes
A couple of small points, mainly on documentation:

- Seems we have lost a lot of python docs
- We need to manually add the properties object to the docs rust

2023-07-25 13:54 UTC, ljeub-pometry commented on raphtory/src/algorithms/triangle_count.rs
> +                println!("adding {} to neighbours of {}", s.id(), t.id());
Yes, this was from testing the subgraph bug, should not be here obviously...

2023-07-25 14:14 UTC, ljeub-pometry commented on raphtory/src/db/api/properties/props.rs
> +    pub fn keys(&self) -> impl Iterator<Item = LockedView<String>> + '_ {
yes

2023-07-25 14:17 UTC, ljeub-pometry commented on raphtory/src/db/graph/vertices.rs
> +    fn properties(&self) -> Self::ValueType<Properties<VertexView<G>>> {
should indeed have it as it is different from the default docstring of the trait

2023-07-25 15:50 UTC, ljeub-pometry commented on raphtory/src/db/api/view/vertex.rs
> +    /// Returns an iterator over properties of the vertices
Agreed, we should do that when we refactor the internal implementations

2023-07-25 16:35 UTC, ljeub-pometry commented
I cleaned up the minor comments and added python docs for the base types. Still need to figure out the best way to document the lists and lists of lists variants

2023-07-26 11:15 UTC, miratepuffin approved these changes

2023-07-26 11:15 UTC, merged