Multiple layers
Pometry/Raphtory pull request #1120
Opened 2023-07-17 14:33 UTC by fabianmurariu

### What changes were proposed in this pull request?

### Why are the changes needed?

### Does this PR introduce any user-facing change? If yes is this documented?

### How was this patch tested?

### Issues

fixes #1036 

### Are there any further changes required?

2023-07-25 09:16 UTC, ljeub-pometry requested changes
We need to fix handling of static properties and check/fix the materialize functionality before we can merge this

2023-07-25 09:16 UTC, ljeub-pometry commented on raphtory/src/db/internal/core_ops.rs
>      fn static_edge_prop(&self, e: EdgeRef, name: &str) -> Option<Prop> {
This is indeed very broken, we need to figure out merging properties across layers!

2023-07-25 09:16 UTC, ljeub-pometry commented on raphtory/src/python/graph/edge.rs
> +    #[pyo3(signature = (layer_names))]
check this signature makes sense

2023-07-25 09:16 UTC, ljeub-pometry commented on raphtory/src/python/graph/edge.rs
> +        if let Some(edge) = self.edge.layer(layer_names.clone().into()) {
Should this return error or option?

2023-07-26 14:48 UTC, fabianmurariu commented on raphtory/src/db/api/view/graph.rs
>              .map(|id| self.get_layer_name_by_id(id))
why not?

2023-07-26 14:48 UTC, fabianmurariu commented on examples/rust/src/bin/crypto/main.rs
> +    let _ = unweighted_page_rank(&g.layer("USDT".into()).unwrap(), 20, None, None, true);
I suppose I could make it take `AsRef<str>`

2023-08-01 14:20 UTC, ljeub-pometry commented on examples/rust/src/bin/crypto/main.rs
> +    let _ = unweighted_page_rank(&g.layer("USDT".into()).unwrap(), 20, None, None, true);
Made this generic now

2023-08-01 14:21 UTC, ljeub-pometry commented on raphtory/src/db/api/view/graph.rs
> +                    }
fixed

2023-08-02 09:05 UTC, Haaroon approved these changes

2023-08-02 09:05 UTC, Haaroon commented on raphtory/src/db/mod.rs.orig
> +<<<<<<< HEAD
Issue in merge

2023-08-02 09:29 UTC, merged