Implement a sum weight algorithm
Pometry/Raphtory pull request #1200
Opened 2023-08-23 21:38 UTC by Haaroon

### What changes were proposed in this pull request?

new algo

### Why are the changes needed?

faster in rust

### Does this PR introduce any user-facing change? If yes is this documented?

yes added docs

### How was this patch tested?

with tests

### Issues

fixed to f64 for now

_If this resolves any issues, please link to them here, the format is a KEYWORD followed by @<ISSUE NUMBER>__
KEYWORDS available are `close`, `closes`, `closed`, `fix`, `fixes`, `fixed`, `resolve`, `resolves`, `resolved`.
Please delete this text before creating your PR 

### Are there any further changes required?

2023-09-04 16:37 UTC, Haaroon commented
cons: many unwraps

2023-09-04 17:00 UTC, miratepuffin requested changes

2023-09-04 17:16 UTC, Haaroon commented on python/tests/test_iterables.py
> +    total = g.vertices.out_edges().properties.get("value_dec").sum().drop_none()
Hmmm, no it's not, fell through the cracks, can add

2023-09-05 14:47 UTC, miratepuffin approved these changes

2023-09-05 14:47 UTC, merged