Added type property to node
Pometry/Raphtory pull request #1480
Opened 2024-02-02 17:39 UTC by Haaroon

### What changes were proposed in this pull request?

### Why are the changes needed?

### Does this PR introduce any user-facing change? If yes is this documented?

### How was this patch tested?

### Issues

_If this resolves any issues, please link to them here, the format is a KEYWORD followed by @<ISSUE NUMBER>__
KEYWORDS available are `close`, `closes`, `closed`, `fix`, `fixes`, `fixed`, `resolve`, `resolves`, `resolved`.
Please delete this text before creating your PR 

### Are there any further changes required?

2024-02-05 14:49 UTC, Haaroon commented
[#1481](https://github.com/Pometry/Raphtory/issues/1481)

2024-02-07 11:54 UTC, ljeub-pometry requested changes
Some minor changes:

- make node type return `Option<ArcStr>` to avoid cloning the actual string and remove the magic `"_default"` node type. 
- make changing the node type an error for the add_node method and add an explicit update_type method on the mutable node view 
- add a test for pandas loading without node type column
- improve `get_node_types` on graph and expose the functionality in the public graph view
- consider improving the import by using the internal methods and only doing the string resolution once (optional, make an issue for later otherwise)
- we should make node type searchable (optional, make an issue for later otherwise)

2024-02-07 11:54 UTC, ljeub-pometry commented on raphtory/src/search/mod.rs
>          let node_id_rev = self.node_index.schema().get_field(fields::VERTEX_ID_REV)?;
should make the node type searchable

2024-02-07 11:55 UTC, ljeub-pometry commented on raphtory/src/core/entities/properties/props.rs
> +    pub fn get_all_node_types(&self) -> Vec<usize> {
probably better, make this return the type names instead by calling `get_keys()`

2024-02-08 11:23 UTC, ljeub-pometry requested changes
`resolve_node_type` still has some logic issues and the related error handling needs to be fixed. We should also add some tests for this (i.e., make sure that overwriting the type errors and doesn't silently fail or change the type and also that a failed update does not actually add the type to the graph).

2024-02-08 11:23 UTC, ljeub-pometry commented on raphtory/src/core/entities/properties/props.rs
> +        }
The assumption is that if you have an internal id, the name entry exists. 

this should be 
```
if id == 0 {
    None
} else {
    Some(self.meta_node_type.get_name(id))
}
```

2024-02-08 11:23 UTC, ljeub-pometry commented on raphtory/src/db/api/mutation/addition_ops.rs
> +        ));
this should not be an expect, just `?`

2024-02-08 11:23 UTC, ljeub-pometry commented on raphtory/src/db/api/mutation/import_ops.rs
> +            .unwrap_or(0usize);
don't unwrap, just error if this fails

2024-02-08 11:23 UTC, ljeub-pometry commented on raphtory/src/db/api/view/graph.rs
> +            let v_type_str = v_type_string.as_str();
If we make `node_type()` return `Option<&ArcStr>` we wouldn't have to do this dance.

2024-02-08 11:23 UTC, ljeub-pometry commented on raphtory/src/db/api/view/graph.rs
> +        let node_a_type_str = node_a_ref.as_deref();
`.as_str()`

2024-02-08 11:23 UTC, ljeub-pometry commented on raphtory/src/db/api/view/graph.rs
> +        );
`as_str()`

2024-02-08 11:23 UTC, ljeub-pometry commented on raphtory/src/db/api/view/internal/core_ops.rs
> +    fn node_type(&self, v: VID) -> Option<ArcStr>;
making this `Option<&ArcStr>` will make our life easier

2024-02-08 11:23 UTC, ljeub-pometry commented on raphtory/src/db/api/view/internal/core_ops.rs
> +    fn node_type(&self, v: VID) -> Option<ArcStr> {
making this Option<&ArcStr> will make our life easier

2024-02-08 11:23 UTC, ljeub-pometry commented on raphtory/src/db/api/view/node.rs
> +    fn node_type(&self) -> Self::ValueType<Option<ArcStr>>;
making this Option<&ArcStr> will make our life easier

2024-02-08 11:23 UTC, ljeub-pometry commented on raphtory/src/db/api/view/node.rs
> +    fn node_type(&self) -> Self::ValueType<Option<ArcStr>> {
making this Option<&ArcStr> will make our life easier

2024-02-08 11:23 UTC, ljeub-pometry commented on raphtory/src/db/internal/core_ops.rs
> +    fn node_type(&self, v: VID) -> Option<ArcStr> {
making this Option<&ArcStr> will make our life easier

2024-02-12 11:47 UTC, Haaroon commented on raphtory/src/core/entities/graph/tgraph.rs
> +                }
add_node_no_props
 calls update_node_type which is why i have the checks in update_node_type,

2024-02-12 13:33 UTC, Haaroon commented
just to note, we cant change the ArcStr to &ArcStr due to the lifetime issues, this is why it was not done before

2024-02-14 15:54 UTC, merged