Improved to_node_df and to_edge_df
Pometry/Raphtory pull request #1537
Opened 2024-03-08 15:33 UTC by Haaroon

### What changes were proposed in this pull request?

### Why are the changes needed?

### Does this PR introduce any user-facing change? If yes is this documented?

### How was this patch tested?

### Issues

_If this resolves any issues, please link to them here, the format is a KEYWORD followed by @<ISSUE NUMBER>__
KEYWORDS available are `close`, `closes`, `closed`, `fix`, `fixes`, `fixed`, `resolve`, `resolves`, `resolved`.
Please delete this text before creating your PR 

### Are there any further changes required?

2024-03-22 10:30 UTC, miratepuffin requested changes
Can you also add these functions onto the edges and nodes object as `.to_df()`

I think we need to make these go significantly faster - but lets get the new version out first.

2024-03-22 10:30 UTC, miratepuffin commented on raphtory/src/python/graph/views/graph_view_modules/export.rs
> +    fn convert_timestamp(time: i64) -> NaiveDateTime {
Can this be changed to include a timezone - history/earliest_time etc do this

2024-03-22 10:30 UTC, miratepuffin commented on raphtory/src/python/graph/views/graph_view_modules/export.rs
> +        mut properties_map: HashMap<String, Prop>,
Doesn't need to be mut

2024-03-22 10:30 UTC, miratepuffin commented on raphtory/src/python/graph/views/graph_view_modules/export.rs
> +    ///     include_property_histories (bool): A boolean, if set to `true`, the history of each property is included, if `false`, only the latest value is shown.  Defaults to `true`.
Should note that this gets ignored when exploding

2024-03-22 10:30 UTC, miratepuffin commented on raphtory/src/python/graph/views/graph_view_modules/export.rs
> +    ///     include_property_histories (bool): A boolean, if set to `true`, the history of each property is included, if `false`, only the latest value is shown.  Defaults to `true`.
Should note that this is ignored when exploding

2024-03-22 17:11 UTC, Haaroon commented
> Can you also add these functions onto the edges and nodes object as `.to_df()`
> 
> I think we need to make these go significantly faster - but lets get the new version out first.

yes done but instead i just moved it to to_df entirely

2024-03-26 10:19 UTC, miratepuffin approved these changes

2024-03-26 10:19 UTC, miratepuffin commented on raphtory/src/python/graph/edges.rs
> +    /// - "properties": The properties of the edge. This column will be included if `include_edge_properties` is set to `true`.
Think this comment is slightly out of date

2024-03-26 10:19 UTC, miratepuffin commented on raphtory/src/python/graph/node.rs
> +    /// - "properties": The properties of the node. This column will be included if `include_node_properties` is set to `true`.
This comment is also slightly out of date

2024-03-26 15:06 UTC, merged