Feature/create node
Pometry/Raphtory pull request #1855
Opened 2024-11-08 16:13 UTC by shivam-880

### What changes were proposed in this pull request?
Add create node api to create node if doesn't already exits. Fail otherwise.
Removes the ability to create RemoteGraph directly, can now only be done through the client

### Why are the changes needed?
An alternative way to create node besides add node which updates the node if node already exists in the graph

### Does this PR introduce any user-facing change? If yes is this documented?
Documentation and Graphql docs

### How was this patch tested?
Unit tests

### Are there any further changes required?
No

2024-11-13 13:37 UTC, ljeub-pometry approved these changes
please run tidy, otherwise looks good

2024-11-13 13:37 UTC, ljeub-pometry commented on python/tests/graphql/edit_graph/test_graphql.py
> +        remote_graph = RemoteGraph(path="g", client=client)
do we not have a `client.remote_graph(path="g")` method?

2024-11-13 13:37 UTC, ljeub-pometry commented on raphtory/src/db/graph/graph.rs
> +        g.create_node(0, 1, [("test".to_string(), Prop::Bool(true))], None)
the `to_string` is not needed, right?

2024-11-13 13:45 UTC, miratepuffin requested changes
Couple of small suggestions and then we can get it in :)

2024-11-15 10:50 UTC, miratepuffin approved these changes

2024-11-15 10:51 UTC, merged