Refactor Node Temporal properties
Pometry/Raphtory pull request #1897
Opened 2024-12-11 11:23 UTC by fabianmurariu

### What changes were proposed in this pull request?
For nodes separate edge originating timestamps from temporal properties originating timestamps

### Why are the changes needed?
Correctness

### Does this PR introduce any user-facing change? If yes is this documented?
API changes

### How was this patch tested?
Tests

### Are there any further changes required?
Yes, design a History struct

2024-12-17 12:22 UTC, ljeub-pometry requested changes
- Some minor things
- I am worried that materialise on a windowed persistent graph is loosing property values

2024-12-17 12:22 UTC, ljeub-pometry commented on raphtory/src/db/api/view/graph.rs
> +                            new_node.node_store_mut().update_t_prop_time(t, prop_offset);
does this handle the property value at the start of the window correctly for a windowed PersistentGraph? Do we have a test for that?

2024-12-17 12:22 UTC, ljeub-pometry commented on raphtory/src/db/api/view/node_property_filter.rs
> +            edges in build_edge_list(2, 10), nodes in build_node_props(50)
is this enough?

2024-12-17 12:22 UTC, ljeub-pometry commented on raphtory/src/db/graph/views/deletion_graph.rs
> +    }
this doesn't handle persistence of property values

2024-12-17 12:22 UTC, ljeub-pometry commented on raphtory/src/db/graph/views/window_graph.rs
> +            .map(|r| r.start..r.end)
could simplify by using `or_else`

2024-12-17 12:22 UTC, ljeub-pometry commented on raphtory/src/python/graph/properties/temporal_props.rs
> +                .filter_map(|(k, v)| (v.len() > 0).then(|| (k, v.into())))
we should discuss the semantics

2024-12-17 16:53 UTC, fabianmurariu commented on raphtory/src/core/storage/lazy_vec.rs
> +    mask: Vec<bool>,
the only benefit is that if you have a few items at the begging then nothing I only push into the `Vec<bool>` not in the ts. 
I don't think there is much of a benefit, perhaps if we ever turn them into arrow there might be.

2024-12-17 17:23 UTC, fabianmurariu commented on raphtory/src/db/api/view/graph.rs
> +                                .update_t_prop_time(TimeIndexEntry::start(earliest), None)
It's actually bad as we might be pulling and edge property into props

2024-12-18 12:19 UTC, fabianmurariu commented on raphtory/src/core/utils/iter.rs
>      }
We'd need different structs for that as GenLockedIter is oblivious to the underlying type of the iterator

2024-12-18 13:03 UTC, fabianmurariu commented on raphtory-graphql/src/model/schema/edge_schema.rs
> +use rustc_hash::FxHashMap;
It's actually needed, the aggregate_schema test fails on the default hashmap

2025-01-08 10:15 UTC, ljeub-pometry approved these changes
LGTM

2025-01-08 10:24 UTC, merged