docs: serialisers
Pometry/Raphtory pull request #260
Opened 2022-03-08 10:00 UTC by rutujasurve94

- [x] `PulsarSerialiser`
- [x] `Avro`
- [x] `Marshal`

2022-03-10 10:50 UTC, ljeub-pometry requested changes

2022-03-10 10:50 UTC, ljeub-pometry commented on src/main/scala/com/raphtory/serialisers/Marshal.scala
> +  *           : deserialise and persist as deep copy by serialising
This is wrong, `a` is the object to copy, not a ClassTag

2022-03-10 10:50 UTC, ljeub-pometry commented on src/main/scala/com/raphtory/serialisers/Marshal.scala
> +  *           : serialise object to Array[Byte]
`t` is not the object being serialised, in fact `t` should almost never be given explicitly as it is a ClassTag that normally should be passed in automatically by the compiler

2022-03-11 14:49 UTC, Haaroon approved these changes

2022-03-11 14:51 UTC, merged